;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; About custom_php.ini        ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; custom_php.ini should contains custom PHP configurations
; custom_php.ini file has been mapped to the location of /etc/php.d in the server
; custom congigurations will apply to the server only after an apache service reload/restart
;
; NOTICE from TechOps
; -------------------
; Each configuration in this file will be considered as a custom configuration and will not be supported by TechOps
;
; debugging
;zend_extension=/usr/lib64/php/modules/xdebug.so

;xdebug.mode=debug,coverage
;xdebug.discover_client_host=true
;xdebug.client_port=9000
;xdebug.log=/var/www/html/xdebug/xdebug.log
; profiling
;xdebug.mode=profile
;xdebug.start_with_request = trigger 
;xdebug.output_dir = /var/www/html/profiling
;xdebug.profiler_output_name = cachegrind.out.%p

;xdebug.mode=coverage
;session.gc_maxlifetime = 720
;session.gc_probability = 1
;session.gc_divisor = 1

